In [1]:
# import requests

# url = "https://raw.githubusercontent.com/ltdaovn/dataset/master/NLP%20with%20Disaster%20Tweets/Disaster_Tweets_train.csv"
# response = requests.get(url)

In [2]:
# with open('Disaster_Tweets_train.csv', 'wb') as file:
#     file.write(response.content)

In [3]:
import pandas as pd

data = pd.read_csv("Disaster_Tweets_train.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5079 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

In [5]:
data['location'] = data['location'].fillna('')
data['keyword'] = data['keyword'].fillna('')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7613 non-null   object
 2   location  7613 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

In [6]:
data.head()

,id,keyword,location,text,target
0,1,,,Our Deeds are the Reason of this #earthquake M...,1
1,4,,,Forest fire near La Ronge Sask. Canada,1
2,5,,,All residents asked to 'shelter in place' are ...,1
3,6,,,"13,000 people receive #wildfires evacuation or...",1
4,7,,,Just got sent this photo from Ruby #Alaska as ...,1

In [7]:
import nltk

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('words')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [8]:
from process_hashtag import extract_hashtags, process_hashtag_string

data['hashtags'] = data['text'].apply(extract_hashtags)
data['hashtags'] = data['hashtags'].apply(process_hashtag_string)

data['text'] = data['text'].str.replace(r'#\w+', '', regex=True)
data['text'] = data['text'] + ' ' + data['hashtags']

data = data.drop(columns=['hashtags'])

data

,id,keyword,location,text,target
0,1,,,Our Deeds are the Reason of this May ALLAH Fo...,1
1,4,,,Forest fire near La Ronge Sask. Canada,1
2,5,,,All residents asked to 'shelter in place' are ...,1
3,6,,,"13,000 people receive evacuation orders in Ca...",1
4,7,,,Just got sent this photo from Ruby as smoke f...,1
...,...,...,...,...,...
7608,10869,,,Two giant cranes holding a bridge collapse int...,1
7609,10870,,,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,,,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,,,Police investigating after an e-bike collided ...,1
7612,10873,,,The Latest: More Homes Razed by Northern Calif...,1

In [9]:
from process_location import process_location

location = pd.read_csv('location.csv')

data['location'] = location['location'].fillna("").apply(process_location)

data["location"].head(50)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31                   birmingha
32                     bristol
33                      africa
34             philadelphia pa
35                   london uk
36                    pretoria
37
38
39              paranaque city
40
41
42
43
44
45
46    greensboronorth carolina
47
48
49                     england
Name: location, dtype: object

In [10]:
from process_keyword import process_keyword

data['keyword'] = data['keyword'].apply(process_keyword)

keyword_list = data['keyword'].to_list()
keyword_set = {keyword for keyword in keyword_list if keyword}

keyword_set

{'ablaze',
 'accident',
 'aftershock',
 'airplane accident',
 'ambulance',
 'annihilated',
 'annihilation',
 'apocalypse',
 'armageddon',
 'army',
 'arson',
 'arsonist',
 'attack',
 'attacked',
 'avalanche',
 'battle',
 'bioterror',
 'bioterrorism',
 'blaze',
 'blazing',
 'bleeding',
 'blew up',
 'blight',
 'blizzard',
 'blood',
 'bloody',
 'blown up',
 'body bag',
 'body bagging',
 'body bags',
 'bomb',
 'bombed',
 'bombing',
 'bridge collapse',
 'buildings burning',
 'buildings on fire',
 'burned',
 'burning',
 'burning buildings',
 'bush fires',
 'casualties',
 'casualty',
 'catastrophe',
 'catastrophic',
 'chemical emergency',
 'cliff fall',
 'collapse',
 'collapsed',
 'collide',
 'collided',
 'collision',
 'crash',
 'crashed',
 'crush',
 'crushed',
 'curfew',
 'cyclone',
 'damage',
 'danger',
 'dead',
 'death',
 'deaths',
 'debris',
 'deluge',
 'deluged',
 'demolish',
 'demolished',
 'demolition',
 'derail',
 'derailed',
 'derailment',
 'desolate',
 'desolation',
 'destroy',
 'destroyed',
 'destruction',
 'detonate',
 'detonation',
 'devastated',
 'devastation',
 'disaster',
 'displaced',
 'drought',
 'drown',
 'drowned',
 'drowning',
 'dust storm',
 'earthquake',
 'electrocute',
 'electrocuted',
 'emergency',
 'emergency plan',
 'emergency services',
 'engulfed',
 'epicentre',
 'evacuate',
 'evacuated',
 'evacuation',
 'explode',
 'exploded',
 'explosion',
 'eyewitness',
 'famine',
 'fatal',
 'fatalities',
 'fatality',
 'fear',
 'fire',
 'fire truck',
 'first responders',
 'flames',
 'flattened',
 'flood',
 'flooding',
 'floods',
 'forest fire',
 'forest fires',
 'hail',
 'hailstorm',
 'harm',
 'hazard',
 'hazardous',
 'heat wave',
 'hellfire',
 'hijack',
 'hijacker',
 'hijacking',
 'hostage',
 'hostages',
 'hurricane',
 'injured',
 'injuries',
 'injury',
 'inundated',
 'inundation',
 'landslide',
 'lava',
 'lightning',
 'loud bang',
 'mass murder',
 'mass murderer',
 'massacre',
 'mayhem',
 'meltdown',
 'military',
 'mudslide',
 'natural disaster',
 'nuclear disaster',
 'nuclear reactor',
 'obliterate',
 'obliterated',
 'obliteration',
 'oil spill',
 'outbreak',
 'pandemonium',
 'panic',
 'panicking',
 'police',
 'quarantine',
 'quarantined',
 'radiation emergency',
 'rainstorm',
 'razed',
 'refugees',
 'rescue',
 'rescued',
 'rescuers',
 'riot',
 'rioting',
 'rubble',
 'ruin',
 'sandstorm',
 'screamed',
 'screaming',
 'screams',
 'seismic',
 'sinkhole',
 'sinking',
 'siren',
 'sirens',
 'smoke',
 'snowstorm',
 'storm',
 'stretcher',
 'structural failure',
 'suicide bomb',
 'suicide bomber',
 'suicide bombing',
 'sunk',
 'survive',
 'survived',
 'survivors',
 'terrorism',
 'terrorist',
 'threat',
 'thunder',
 'thunderstorm',
 'tornado',
 'tragedy',
 'trapped',
 'trauma',
 'traumatised',
 'trouble',
 'tsunami',
 'twister',
 'typhoon',
 'upheaval',
 'violent storm',
 'volcano',
 'war zone',
 'weapon',
 'weapons',
 'whirlwind',
 'wild fires',
 'wildfire',
 'windstorm',
 'wounded',
 'wounds',
 'wreck',
 'wreckage',
 'wrecked'}

In [11]:
data['keyword'] = data.apply(
    lambda row: next(
        (keyword for keyword in keyword_set if keyword in row['text']), '')
    if row['keyword'] == '' else row['keyword'], axis=1
)

In [12]:
from process_text import process_text

data['text'] = data['text'].apply(process_text)
data = data[data['text'].notna() & (data['text'] != '')]

data.to_csv("processed_data.csv", index=False)

In [5]:
import pandas as pd

new_data = pd.read_csv('processed_data.csv')

new_data = new_data.drop(columns=['id', 'keyword', 'location'])

new_data.reset_index()

new_data.head()

new_data.to_csv('final_data.csv', index=False)